---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

# vars:
# env:
# includes:

tasks:
  default: task -l

  init:
    desc: Initialize The Project
    cmds:
      - cmd: echo Initializing the project
        silent: true
      - cmd: echo "Installing dependencies..."
        silent: true
      - cmd: npm install --global npm@11.2.0 >> /dev/null
        silent: true
      - cmd: npm add --global nx@latest >> /dev/null
        silent: true
      - cmd: npm install --global pnpm@latest >> /dev/null
        silent: true
      - cmd: pnpm install >> /dev/null
        silent: true
      - cmd: echo "Installing dependencies complete"
        silent: true
      - cmd: sleep 5
        silent: true
      #- cmd: clear

  check-port:
    desc: "Check if port 3000 is in use and kill the process if it is"
    silent: true
    cmds:
      - echo Checking port 3000 and killing process if it is in use
      - lsof -i :3000 | grep LISTEN | awk '{print $2}' | xargs kill -9
      - echo Task Complete
