name: Assign people to issues and pull requests
on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v1
        with:
          numOfAssignee: 1
          allowSelfAssign: true
          assignees: Sinless777
          abortIfPreviousAssignees: false
